version: "3.9"
name: baja-la-bruja-composer
services:
  mle:
    build:
      dockerfile: ./website/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - PORT=8080
      - MONGO_DB=mongodb://mongodb:27017/shop
    networks:
      - node-network
  
  mongodb:
    image: mongo:6-jammy
    ports:
      - "27017:27017"
    volumes:
      - dbdata6:/data/db
    networks:
      - node-network

volumes:
  dbdata6:

networks:
  node-network:
    driver: bridge